### ISSUE TITLE
Importerror:dynamic module does not define module export function(PyInit_polyiou)

### ISSUE THREAD

**Issue by Adoreee** [CAPTAIN-WHU/DOTA_devkit#10]
I use ResultMerge.py to merge the results. 
I have generated _ployiou.so using SWIG, why do I get the **_Importerror:dynamic module does not define module export function(PyInit__polyiou)_** when I run ResultMerge.py?

**Comment by dingjiansw101** [comment]
The python interpreter that you compiler maybe not the same interpreter that you used to import.

**Comment by Adoreee** [comment]
Thank U.
I have solved it,  this problem does not occur with Python 2.7.
