### ISSUE TITLE
.txt 的坐标， 代表的是什么位置？？

### ISSUE THREAD

**Issue by mantou22** [CAPTAIN-WHU/DOTA_devkit#12]
您好，请问
807 331 800 324 817 309 823 316 ship 0
[(x1, y1), (x2, y2), (x3, y3), (x4, y4)] 分别代表的是什么地方的坐标位置？

**Comment by dingjiansw101** [comment]
四边形的四个顶点，具体参见论文或网站描述，或者你可以可视化出来看下。

Dai wenxin <notifications@github.com> 于2018年10月11日周四 下午10:13写道：
