### ISSUE TITLE
iou < 0

### ISSUE THREAD

**Issue by NickMinYang** [CAPTAIN-WHU/DOTA_devkit#14]
你好，我把polyiou.cpp移植到caffe中，发现算出来的iou是负的
然后我把对应的坐标放到polyiou.py中测试，确实是负的
这是什么问题？

if __name__ == '__main__':
    p = [0.917691,0.197127,0.972934,0.197127,0.972934,0.224748,0.917691,0.224748]
    q = [0.208984,0.03125,0.300781,0.0332031,0.300781,0.0703125,0.216797,0.0703125]
    iou = iou_poly(p, q)
    print('iou:',iou)

**Comment by dingjiansw101** [comment]
These two polygons do not intersect. Thus, the result is -3.5e-16, almost the same as 0. This is the problem of calculating accuracy， not a bug.

**Comment by NickMinYang** [comment]
这种情况呢？cpp代码跑出来的结果
,0.941406,0.660156,0.980469,0.660156,0.980469,0.699219,0.941406,0.699219
,0.541016,0.318359,0.998047,0.105469,0.998047,0.253906,0.589844,0.439453
inter_area:0.0413624
union_area:0.0233292
iou:1.77299

**Comment by dingjiansw101** [comment]
I get a different result from yours. 
https://paste.ubuntu.com/p/Qkj5vcygyJ/

**Comment by NickMinYang** [comment]
@dingjiansw101 

两个问题：
1.x,y没有初始化？
struct Point {
    double x,y; Point(){} //x,y没有初始化？
    Point(double x,double y):x(x),y(y){}
    bool operator==(const Point&p)const{
        return sig(x-p.x)==0 && sig(y-p.y)==0;
    }
};

2.static 多线程会有问题？
void polygon_cut(Point*p,int&n,Point a,Point b){
    static Point pp[maxn]; //static 多线程会有问题？
    int m=0;p[n]=p[0];
    for(int i=0;i<n;i++){
        if(sig(cross(a,b,p[i]))>0) pp[m++]=p[i];
        if(sig(cross(a,b,p[i]))!=sig(cross(a,b,p[i+1])))
            lineCross(a,b,p[i],p[i+1],pp[m++]);
    }
    n=0;
    for(int i=0;i<m;i++)
        if(!i||!(pp[i]==pp[i-1]))
            p[n++]=pp[i];
    while(n>1&&p[n-1]==p[0])n--;
}

**Comment by makefile** [comment]
确实会出问题, static局部变量在多线程情况下并发写入导致结果不正确. x,y是否需要初始化不太清楚, 保险起见, 可将Point pp[maxn]数组初始化为0. @NickMinYang

**Comment by dingjiansw101** [comment]
多线程的情况下使用static确实不正确
