### ISSUE TITLE
Possible bug in dota_evaluation_task2.py

### ISSUE THREAD

**Issue by makefile** [CAPTAIN-WHU/DOTA_devkit#15]
I think there is a bug at [dota_evaluation_task2.py](https://github.com/CAPTAIN-WHU/DOTA_devkit/blob/master/dota_evaluation_task2.py#L32) start from Line 32.
In function parse_gt the bbox coordinate is got from quadrangle box index of 0,1,4,5 instead of the bounding rectangle (xmin ymin, xmax, ymax).

**Comment by dingjiansw101** [comment]
On our evaluation server, the ground truth of task2 is converted to be the 4 coordinates of the axis-aligned bounding box of the original annotation. So it is correct. You can visulize the [Task2_gt](https://pan.baidu.com/s/1kWyRGaz#list/path=%2FDOTA%2Ftrain%2FlabelTxt&parentPath=%2FDOTA) to confirm it.

**Comment by makefile** [comment]
Yeah, I see. I didn't know there is a Task2_gt before.
