### ISSUE TITLE
import _polyiou ImportError: No module named '_polyiou'

### ISSUE THREAD

**Issue by tangjiuqi097** [CAPTAIN-WHU/DOTA_devkit#2]
I run the demo in pycharm, and meet this issue.
My system is ubuntu14.04 and python vesion is 3.4

![image](https://user-images.githubusercontent.com/22868536/39393086-749253f0-4af3-11e8-826e-6b911025bccf.png)

The builded files like this.

![image](https://user-images.githubusercontent.com/22868536/39393002-67870e9a-4af2-11e8-9e3a-1d93b1749a5b.png)

**Comment by tangjiuqi097** [comment]
It is because I build it with another conda envs. I rebuild and solve this problem. Thanks a lot.

**Comment by dalmiaman** [comment]
@tangjiuqi097 Can you please tell me what exactly you did to solve this problem? If I run the following command:
```
env MACOSX_DEPLOYMENT_TARGET=10.14 python3 setup.py build_ext --inplace
```

It works correctly. However, I still get the import error. I am working with a conda env on a Mac OS. Any help would be appreciated!

**Comment by dingjiansw101** [comment]
Have you activated the conda when you execute the command?
