### ISSUE TITLE
polyiou.py error (NotImplementedError: Wrong number or type of arguments for overloaded function 'new_VectorDouble'.)

### ISSUE THREAD

**Issue by Li-Chengyang** [CAPTAIN-WHU/DOTA_devkit#23]
Anyone encounter this issue?

File "/home/zero/detection/polyiou/polyiou.py", line 130, in __init__
    this = _polyiou.new_VectorDouble(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_VectorDouble'.
  Possible C/C++ prototypes are:
    std::vector< double >::vector()
    std::vector< double >::vector(std::vector< double > const &)
    std::vector< double >::vector(std::vector< double >::size_type)
    std::vector< double >::vector(std::vector< double >::size_type,std::vector< double >::value_type const &)

**Comment by Li-Chengyang** [comment]
solved.

**Comment by HsLOL** [comment]
> Anyone encounter this issue?
> 
> File "/home/zero/detection/polyiou/polyiou.py", line 130, in **init**
> this = _polyiou.new_VectorDouble(*args)
> NotImplementedError: Wrong number or type of arguments for overloaded function 'new_VectorDouble'.
> Possible C/C++ prototypes are:
> std::vector< double >::vector()
> std::vector< double >::vector(std::vector< double > const &)
> std::vector< double >::vector(std::vector< double >::size_type)
> std::vector< double >::vector(std::vector< double >::size_type,std::vector< double >::value_type const &)

I met the same problem.

`            for index in range(len(anchor_vertex[:1])):
                single_anchor = anchor_vertex[index]
                single_rotation_opencv_format = hor_positive_assigned_annotations[index][:5]
                single_rotation_box = single_Rectangle_area(single_rotation_opencv_format)
                single_points = Rotation2points(single_rotation_box)
                print(f"single_points: {single_points}\nsingle_anchor: {single_anchor}")
                print(type(single_points))
                print(type(single_anchor))

                # example input for polyiou.iou_poly() function
                temp1 = [433.16364, 186.74037, 421.0, 172.99998, 482.83636, 118.2596, 495.0, 131.99998]
                temp2 = [282.6015831685088, 114.6015831685088, 333.3984168314912, 114.6015831685088, 333.3984168314912, 165.3984168314912, 282.6015831685088, 165.3984168314912]
                print(type(temp2))
                skew_IoU = polyiou.iou_poly(polyiou.VectorDouble(list(single_points)), polyiou.VectorDouble(list(single_anchor)))
                skew_IoU = polyiou.iou_poly(polyiou.VectorDouble(temp1), polyiou.VectorDouble(temp2))
                skew_IoU_lists.append(skew_IoU)
                print(skew_IoU)`

the single_points and the single_anchor is the same as the temp1 and the temp2( include value and type).
But the temp1 and the temp2 have the result, single_points and single_anchor has no result.

Did you encounter this issue?

**Comment by msohail95** [comment]
Hello
I'm facing exactly same issue. Could you please help me with it.
I am trying to detect oriented object in Ariel images but the code is causing this problem.

TypeError: Wrong number or type of arguments for overloaded function 'new_VectorDouble'.
  Possible C/C++ prototypes are:
    std::vector< double >::vector()
    std::vector< double >::vector(std::vector< double > const &)
    std::vector< double >::vector(std::vector< double >::size_type)
    std::vector< double >::vector(std::vector< double >::size_type,std::vector< double >::value_type const &)

**Comment by msohail95** [comment]
> solved.

how did you resolved this issue?
thank you

**Comment by msohail95** [comment]
> > solved.
> 
> how did you resolved this issue? thank you

resolved.
Changed the type of vector being passed to float
