### ISSUE TITLE
How to merge the slipt images?

### ISSUE THREAD

**Issue by wen0618** [CAPTAIN-WHU/DOTA_devkit#25]
请问怎么合并裁剪过的DOTA数据集的输出？
我用官方的faster rcnn框架测试分割过oriented bbox格式输入，
得到按图片名字命名的txt文档输出，但是不懂怎么用resultmerge文件合并成安类分的txt文档。
能给个示例吗？

**Comment by Yanhong-Li** [comment]
我也想知道，你解决了吗？
