### ISSUE TITLE
No module named 'dota_utils'

### ISSUE THREAD

**Issue by s-s-wang** [CAPTAIN-WHU/DOTA_devkit#42]
When the training code is executed in the home directory，it report error "No module named 'dota_utils'". But the dota_utils.py is under the DOTA_devkit files.

**Comment by ulanbator** [comment]
你好，我遇到了和你一样的问题，请问你是怎么解决的呢？

**Comment by YoonaIAN** [comment]
hello，Have you solved it？

**Comment by Amourship** [comment]
sys.path.append('xxx') , xxx is your DOTA_devkit path
