### ISSUE TITLE
what does the function "lineCross()" do?

### ISSUE THREAD

**Issue by Rhapso** [CAPTAIN-WHU/DOTA_devkit#9]
the function is from polyiou.cpp. would you explain the code below in details?
```c++
p.x=(c.x*s2-d.x*s1)/(s2-s1);
p.y=(c.y*s2-d.y*s1)/(s2-s1);
```

**Comment by dingjiansw101** [comment]
It calculates the cross point of two segments. If you want more details, you need search for some material about calculate geometry.

**Comment by Rhapso** [comment]
I see, thank you!

----- 原始邮件 -----
发件人: "Jian Ding" <notifications@github.com>
收件人: "CAPTAIN-WHU/DOTA_devkit" <DOTA_devkit@noreply.github.com>
抄送: "your mr fan" <your_mr_fan@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期三, 2018年 8 月 29日 上午 11:57:58
主题: Re: [CAPTAIN-WHU/DOTA_devkit] what does the function "lineCross()" do? (#9)

It calculates the cross point of two segments. If you want more details, you need search for some material about calculate geometry.

**Comment by Rhapso** [comment]
I see, thank you!
